"""
pysurfacefun
============

High-order fast direct solvers for partial differential equations on smooth
surfaces.

Surfaces are discretized by curved high-order patches -- tensor-product
Chebyshev quadrilaterals (:class:`SurfaceMesh`) or Proriol-Koornwinder-Dubiner
triangles (:class:`TriangleSurfaceMesh`).  Elliptic operators with constant or
variable coefficients are inverted with a hierarchical Poincare--Steklov (HPS)
fast direct solver whose merge order is chosen by nested dissection, and
reaction--diffusion systems are advanced with high-order IMEX time steppers
that reuse the factorization.

Quick start::

    import pysurfacefun as psf

    dom = psf.sphere(n=12, nref=1)
    f = psf.field(lambda x, y, z: x * y * z, dom)

    problem = psf.SurfaceProblem(dom, variables="u", namespace={"f": f})
    problem.add_equation("-lap(u) + 2*u = 14*f")
    u = problem.solve()
"""

from __future__ import annotations

from .core import (
    PDO,
    SurfaceFunction,
    SurfaceMesh,
    SurfaceOp,
    SurfaceVectorFunction,
    boundingbox,
    chebpts,
    chebpts2,
    compose,
    conj,
    cos,
    cross,
    diffmat,
    diffx,
    diffy,
    diffz,
    dot,
    exp,
    from_rhino,
    imag,
    log,
    log10,
    maxEst,
    mean2,
    minEst,
    normal,
    normalize,
    patch_orientation,
    plot_surface,
    plot_vector_field,
    prolong,
    randnfun3,
    real,
    real_spherical_harmonic,
    sin,
    smooth_random_function_3d,
    solve_laplace_beltrami_sphere,
    sphere,
    sqrt,
    stellarator,
    sum2,
    surfacearea,
    surfacefun,
    surfacefunv,
    torus,
    write_vtu,
)
from .evaluator import (
    EvaluationRecord,
    EvaluationTask,
    Evaluator,
    JSONLinesOutputHandler,
    NPZOutputHandler,
    OutputHandler,
    VTKOutputHandler,
)
from .hps import HPSSolver, LeafOperators, nested_dissection_tree
from .operators import HPSOperator, parse_pdo
from .problems import (
    SurfaceEquation,
    SurfaceIVP,
    SurfaceIVPSolver,
    SurfaceLBVP,
    SurfaceLBVPSolver,
    SurfaceProblem,
)
from .timesteppers import SCHEMES, get_scheme
from .tri import (
    LevelSetSurface,
    TriangleSurfaceFunction,
    TriangleSurfaceMesh,
    TriangleSurfaceOp,
    TriangleSurfaceVectorFunction,
    extract_tri_mesh_arrays,
    icosphere_tri,
    koornwinder_pkd,
    levelset_surface,
    levelset_surface_quad,
    levelset_surface_tri,
    levelset_surface_tri_from_mat,
    load_mat_surface_mesh,
    load_mat_tri_mesh,
    node_family_points,
    orient_tri_faces_outward,
    plot_tri_surface,
    plot_wireframe,
    project_to_levelset,
    recursive_nodes,
    reference_triangle_quadrature_weights,
    refine_quad_mesh,
    refine_surface_mesh,
    refine_tri_mesh,
    shifted_lobatto_nodes,
    surface_mesh_arrays,
    tri_diff,
    tri_edge_indices,
    tri_integral2,
    tri_lap,
    tri_patch_boundary_segments,
    tri_reference_nodes,
    tri_resample,
    tri_resample_mesh,
    tri_resampled_patch_geometry,
    tri_resampled_patch_values,
    tri_strong_diffmat,
    tri_surfacearea,
    tri_surfacefun,
    tri_surfaceop,
    tri_wireframe_edge_indices,
    triangle_boundary_meshio_mesh,
    triangle_meshio_mesh,
    triangle_surface_mesh_arrays,
    triangulate_faces,
    trilattice,
    wireframe,
    write_tri_patch_boundaries_vtp,
    write_tri_vtp,
    write_tri_vtu,
    write_triangle_meshio,
)
from .unified import (
    SurfaceDomain,
    SurfaceField,
    SurfaceVectorField,
    apply_operator,
    diff,
    div,
    divergence,
    field,
    grad,
    gradient,
    hodge,
    integral,
    integral2,
    lap,
    laplacian,
    norm,
    resample,
    resample_mesh,
    surfaceop,
    vector_field,
    vector_norm,
)
from .vtk import write_mesh_vtu, write_vtu_fields

__version__ = "0.2.0"

__all__ = [
    "PDO",
    "SCHEMES",
    "EvaluationRecord",
    "EvaluationTask",
    "Evaluator",
    "HPSOperator",
    "HPSSolver",
    "JSONLinesOutputHandler",
    "LeafOperators",
    "LevelSetSurface",
    "NPZOutputHandler",
    "OutputHandler",
    "SurfaceDomain",
    "SurfaceEquation",
    "SurfaceField",
    "SurfaceFunction",
    "SurfaceIVP",
    "SurfaceIVPSolver",
    "SurfaceLBVP",
    "SurfaceLBVPSolver",
    "SurfaceMesh",
    "SurfaceOp",
    "SurfaceProblem",
    "SurfaceVectorField",
    "SurfaceVectorFunction",
    "TriangleSurfaceFunction",
    "TriangleSurfaceMesh",
    "TriangleSurfaceOp",
    "TriangleSurfaceVectorFunction",
    "VTKOutputHandler",
    "__version__",
    "apply_operator",
    "boundingbox",
    "chebpts",
    "chebpts2",
    "compose",
    "conj",
    "cos",
    "cross",
    "diff",
    "diffmat",
    "diffx",
    "diffy",
    "diffz",
    "div",
    "divergence",
    "dot",
    "exp",
    "extract_tri_mesh_arrays",
    "field",
    "from_rhino",
    "get_scheme",
    "grad",
    "gradient",
    "hodge",
    "icosphere_tri",
    "imag",
    "integral",
    "integral2",
    "koornwinder_pkd",
    "lap",
    "laplacian",
    "levelset_surface",
    "levelset_surface_quad",
    "levelset_surface_tri",
    "levelset_surface_tri_from_mat",
    "load_mat_surface_mesh",
    "load_mat_tri_mesh",
    "log",
    "log10",
    "maxEst",
    "mean2",
    "minEst",
    "nested_dissection_tree",
    "node_family_points",
    "norm",
    "normal",
    "normalize",
    "orient_tri_faces_outward",
    "parse_pdo",
    "patch_orientation",
    "plot_surface",
    "plot_tri_surface",
    "plot_vector_field",
    "plot_wireframe",
    "project_to_levelset",
    "prolong",
    "randnfun3",
    "real",
    "real_spherical_harmonic",
    "recursive_nodes",
    "reference_triangle_quadrature_weights",
    "refine_quad_mesh",
    "refine_surface_mesh",
    "refine_tri_mesh",
    "resample",
    "resample_mesh",
    "shifted_lobatto_nodes",
    "sin",
    "smooth_random_function_3d",
    "solve_laplace_beltrami_sphere",
    "sphere",
    "sqrt",
    "stellarator",
    "sum2",
    "surface_mesh_arrays",
    "surfacearea",
    "surfacefun",
    "surfacefunv",
    "surfaceop",
    "torus",
    "tri_diff",
    "tri_edge_indices",
    "tri_integral2",
    "tri_lap",
    "tri_patch_boundary_segments",
    "tri_reference_nodes",
    "tri_resample",
    "tri_resample_mesh",
    "tri_resampled_patch_geometry",
    "tri_resampled_patch_values",
    "tri_strong_diffmat",
    "tri_surfacearea",
    "tri_surfacefun",
    "tri_surfaceop",
    "tri_wireframe_edge_indices",
    "triangle_boundary_meshio_mesh",
    "triangle_meshio_mesh",
    "triangle_surface_mesh_arrays",
    "triangulate_faces",
    "trilattice",
    "vector_field",
    "vector_norm",
    "wireframe",
    "write_mesh_vtu",
    "write_tri_patch_boundaries_vtp",
    "write_tri_vtp",
    "write_tri_vtu",
    "write_triangle_meshio",
    "write_vtu",
    "write_vtu_fields",
]
